-- Batch 1 Ingredient Updates
-- Run in Supabase SQL Editor: https://supabase.com/dashboard/project/rqmplfyuonkikdmqngrj/sql

BEGIN;

UPDATE products SET ingredients = ARRAY['Aqua/Water/Eau', 'Lauramidopropyl Hydroxysultaine', 'Sodium Cocoyl Isethionate', 'Cocamide MIPA', 'Betaine', 'Ricinus Communis (Castor) Seed Oil', 'Sodium Isethionate', 'Cetearyl Alcohol', 'Sodium Chloride', 'Piroctone Olamine', 'Ceramide NP', 'Ceramide EOP', 'Ceramide AP', 'Phytosphingosine', 'Zanthoxylum Bungeanum Pericarp Extract', 'Phytosterols', 'Hydroxypropyl Bislauramide MEA', 'Hydroxypropyl Bisstearamide MEA', 'Mentha Piperita (Peppermint) Oil', 'Melaleuca Alternifolia (Tea Tree) Leaf Oil', 'Menthol', 'Olea Europaea (Olive) Fruit Oil', 'Polyglyceryl-10 Laurate', 'Glycol Stearate', 'Glyceryl Stearate', 'Sodium Lauroyl Lactylate', 'Sodium Cocoyl Glutamate', 'Coconut Acid', 'Glycerin', 'Polyquaternium-7', 'Stearic Acid', 'Trisodium Dicarboxymethyl Alaninate', 'Hydroxypropyl Cyclodextrin', 'Caprylyl Glycol', 'Ethylhexylglycerin', 'Sodium Benzoate', 'Potassium Sorbate', 'Citric Acid', 'Limonene'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = '8412ed93-529e-48ea-b5ac-ecbd47f43f66';

UPDATE products SET ingredients = ARRAY['Aqua/Water', 'Coco-Glucoside', 'Glycerin', 'Parfum/Fragrance', 'Citric Acid', 'Salicylic Acid', 'Potassium Hydroxide', 'Linalool', 'Hydroxypropyl Guar Hydroxypropyltrimonium Chloride', 'Aloe Barbadensis Leaf Juice', 'Limonene', 'Geraniol', 'Citral', 'Potassium Sorbate', 'Sodium Benzoate'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = 'b2105321-ec01-45de-aeac-7fdb5e69fc23';

UPDATE products SET ingredients = ARRAY['Water/Aqua/Eau', 'Sodium C14-16 Olefin Sulfonate', 'Cocamidopropyl Betaine', 'Decyl Glucoside', 'Glycerin', 'Sodium Methyl Cocoyl Taurate', 'Collagen', 'Sodium Hyaluronate', 'Cocos Nucifera (Coconut) Oil', 'Jojoba Esters', 'Linum Usitatissimum (Linseed) Seed Oil', 'Olea Europaea (Olive) Fruit Oil', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'Hydrolyzed Quinoa', 'Butyrospermum Parkii (Shea) Butter', 'Hydrolyzed Vegetable Protein PG-Propyl Silanetriol', 'Hydroxypropylgluconamide', 'Hydroxypropylammonium Gluconate', 'Hydroxypropyl Guar Hydroxypropyltrimonium Chloride', 'Panthenol', 'Coconut Acid', 'Tocopherol', 'Cocoglucosides Hydroxypropyltrimonium Chloride', 'Guar Hydroxypropyltrimonium Chloride', 'Polyquaternium-7', 'Acrylates Copolymer', 'Cocamide MIPA', 'Citric Acid', 'Tartaric Acid', 'Chlorphenesin', 'Disodium EDTA', 'Propanediol', 'PEG-150 Distearate', 'Sodium Benzoate', 'Sodium Chloride', 'Sodium Hydroxide', 'Sodium Lauroyl Glycinate', 'Isopropanolamine', 'Tetrasodium Glutamate Diacetate', 'Ethylhexylglycerin', 'Leuconostoc/Radish Root Ferment Filtrate', 'Potassium Sorbate', 'Benzyl Alcohol', 'Phenoxyethanol'], flagged_ingredients = '[{"ingredient": "Sodium C14-16 Olefin Sulfonate", "reason": "sulfate"}]'::jsonb, cg_status = 'not_approved', updated_at = now() WHERE id = 'e826160e-52d0-445c-af32-c606313bc904';

UPDATE products SET ingredients = ARRAY['Water/Aqua', 'Cetyl Alcohol', 'Cetearyl Alcohol', 'Behentrimonium Methosulfate', 'Cetrimonium Chloride', 'Cocamidopropyl Betaine', 'PEG-7 Olivate', 'Guar Hydroxypropyltrimonium Chloride', 'Tetrasodium EDTA', 'Hydrolyzed Oat Flour', 'Mentha Piperita (Peppermint) Leaf Extract', 'Matricaria Recutita (Chamomile) Flower Extract', 'Yucca Leaf Extract', 'Urtica Dioica (Nettle) Leaf Extract', 'Melissa Officinalis (Melissa) Leaf Extract', 'Polysorbate 60', 'Equisetum Arvense (Horsetail) Leaf Extract', 'Tocopheryl Acetate', 'Phenoxyethanol', 'Caprylyl Glycol', 'Fragrance/Parfum', 'Benzyl Benzoate', 'Limonene'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = '03257c96-661b-4d0c-90d2-6942115e9315';

UPDATE products SET ingredients = ARRAY['Water/Aqua/Eau', 'Stearyl Alcohol', 'Behentrimonium Chloride', 'Cetyl Alcohol', 'Hydroxypropyl Starch Phosphate', 'Sodium Lauroamphoacetate', 'Anastatica Hierochuntica Extract', 'Rice Bran Oil/Hydrogenated Rice Bran Oil Esters', 'Cocamidopropyl Hydroxysultaine', 'Citric Acid', 'Ceteareth-20', 'Disodium EDTA', 'Hydroxypropyl Bis-Hydroxyethyldimonium Chloride', 'Sodium Chloride', 'Butylene Glycol', 'Caprylyl Glycol', 'Hexylene Glycol', 'Methylchloroisothiazolinone', 'Methylisothiazolinone', 'Phenoxyethanol', 'Benzyl Salicylate', 'Citronellol', 'Coumarin', 'Hexamethylindanopyran', 'Hydroxycitronellal', 'Limonene', 'Terpineol', 'Tetramethyl Acetyloctahydronaphthalenes', 'Vanillin', 'Citrus Aurantium Peel Oil', 'Citrus Limon Peel Oil', 'Fragrance (Parfum)'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = '5ed6bb8f-25d1-4827-8ee4-8e75462faaf6';

UPDATE products SET ingredients = ARRAY['Aqua/Water/Eau', 'Cetearyl Alcohol', 'Glycerin', 'Cetyl Esters', 'Cetyl Alcohol', 'Stearamidopropyl Dimethylamine', 'Behentrimonium Chloride', 'Butyrospermum Parkii (Shea) Butter', 'Helianthus Annuus (Sunflower) Seed Oil', 'Propanediol', 'Prunus Amygdalus Dulcis (Sweet Almond) Oil', 'Carthamus Tinctorius (Safflower) Seed Oil', 'Ricinus Communis (Castor) Seed Oil', 'Helianthus Annuus (Sunflower) Extract', 'Rosmarinus Officinalis (Rosemary) Leaf Extract', 'Oryza Sativa (Rice) Bran Extract', 'Euterpe Oleracea Fruit Extract', 'Eucalyptus Globulus Leaf Oil', 'Mauritia Flexuosa Fruit Oil', 'Morinda Citrifolia Fruit Extract', 'Cymbopogon Schoenanthus Extract', 'Garcinia Indica Seed Butter', 'Sclerocarya Birrea Seed Oil', 'Hydrolyzed Rice Protein', 'Aloe Barbadensis Leaf Juice', 'Palmitoyl Tetrapeptide-20', 'Squalane', 'Tocopherol', 'Hydroxyethylcellulose', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'Hydrogenated Castor Oil/Sebacic Acid Copolymer', 'BHT', 'Panthenol', 'Polysorbate 60', 'Guar Hydroxypropyltrimonium Chloride', 'Stearamine Oxide', 'Ethylhexyl Olivate', 'Diheptyl Succinate', 'Isododecane', 'Citric Acid', 'Disodium EDTA', 'Tetrasodium EDTA', 'Sodium Hydroxide', 'Disodium Phosphate', 'Sodium Phosphate', 'Butylene Glycol', 'Caprylyl Glycol', 'Hexylene Glycol', 'Sodium Benzoate', 'Potassium Sorbate', 'Leuconostoc/Radish Root Ferment Filtrate', 'Chlorphenesin', 'Phenoxyethanol', 'Limonene', 'Linalool', 'Fragrance (Parfum)'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = '9881a3b0-d98f-45ac-a5b3-463a3fa1d7f0';

UPDATE products SET ingredients = ARRAY['Water (Aqua)', 'Cetearyl Alcohol', 'Hydroxypropyl Starch Phosphate', 'Cetyl Palmitate', 'Orbignya Speciosa (Babassu) Kernel Oil', 'Behentrimonium Chloride', 'Astrocaryum Murumuru Seed Butter', 'Butyrospermum Parkii (Shea) Butter', 'Humulus Lupulus (Hops) Extract', 'Jasminum Officinale (Jasmine) Flower Extract', 'Citrus Limon (Lemon) Peel Extract', 'Panthenol', 'Glycerin', 'Guar Hydroxypropyltrimonium Chloride', 'Glyceryl Caprylate', 'Glyceryl Undecylenate', 'Citric Acid', 'Disodium EDTA', 'Tocopherol', 'Potassium Sorbate', 'Sodium Benzoate', 'Sodium Hydroxide'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = 'b15fe4bd-e0f6-4867-b14d-b2756be9e911';

UPDATE products SET ingredients = ARRAY['Water (Aqua)', 'Ricinus Communis (Castor) Seed Oil', 'Cetearyl Alcohol', 'Dicaprylyl Carbonate', 'Behentrimonium Chloride', 'Orbignya Speciosa (Babassu) Kernel Oil', 'Panthenol', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'Astrocaryum Murumuru Seed Butter', 'Cucurbita Pepo (Pumpkin) Seed Extract', 'Opuntia Tuna (Prickly Pear) Fruit Extract', 'Ribes Nigrum (Black Currant) Fruit Extract', 'Psidium Guajava (Guava) Fruit Extract', 'Brassica Oleracea Acephala (Kale) Leaf Extract', 'Lentinus Edodes (Shiitake Mushroom) Extract', 'Hydroxypropylgluconamide', 'Hydroxypropylammonium Gluconate', 'Hydrolyzed Hemp Seed Extract', 'Hydrolyzed Rice Protein', 'Butyrospermum Parkii (Shea) Butter', 'Glycerin', 'Polyquaternium-10', 'Guar Hydroxypropyltrimonium Chloride', 'Ethylhexylglycerin', 'Tartaric Acid', 'Citric Acid', 'Disodium EDTA', 'Sodium Benzoate', 'Potassium Sorbate', 'Phenoxyethanol', 'Sodium Hydroxide', 'Benzyl Alcohol', 'Linalool', 'Limonene', 'Geraniol', 'Citronellol', 'Fragrance (Parfum)'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = 'c3d6db66-675f-4dbc-b158-cb8e53f30a9e';

UPDATE products SET ingredients = ARRAY['Water/Aqua/Eau', 'Cetearyl Alcohol', 'Coco-Betaine', 'Hydroxypropyl Starch Phosphate', 'Behentrimonium Chloride', 'Orbignya Oleifera (Babassu) Seed Oil', 'Tapioca Starch', 'Aloe Barbadensis Leaf Juice', 'Adansonia Digitata Seed Oil', 'Hydrolyzed Wheat Protein', 'Polyquaternium-10', 'Maltodextrin', 'Citric Acid', 'Fragrance (Parfum)', 'Linalool', 'Eugenol', 'Geraniol', 'Citronellol', 'Citral', 'Limonene', 'Potassium Sorbate', 'Phenoxyethanol'], flagged_ingredients = '[]'::jsonb, cg_status = 'approved', updated_at = now() WHERE id = 'bd4fb3de-239e-4b1f-9af5-945a6f434163';

UPDATE products SET ingredients = ARRAY['Water', 'Sodium Laureth Sulfate', 'Ammonium Lauryl Sulfate', 'Cocamidopropyl Betaine', 'Glycerin', 'Phenoxyethanol', 'Fragrance', 'Decyl Glucoside', 'Trimethylolpropane Tricaprylate/Tricaprate', 'Cetyl Alcohol', 'Glyceryl Distearate', 'Dimethicone', 'PEG-150 Distearate', 'Cocamide MIPA', 'PCA Dimethicone', 'Potassium Sorbate', 'Citric Acid', 'Melaleuca Alternifolia (Tea Tree) Leaf Oil', 'Cetyl Triethylmonium Dimethicone PEG-8 Succinate', 'Disodium EDTA', 'Hydrogenated Polydecene', 'Panthenyl Ethyl Ether', 'Polyquaternium-10', 'Polyquaternium-7', 'Sodium Coco PG-Dimonium Chloride Phosphate', 'Caprylyl Glycol', 'Hexylene Glycol', 'Magnesium Chloride', 'Magnesium Nitrate', 'Cysteine', 'Glycine', 'Histidine', 'Leucine', 'Tyrosine', 'Lavandula Angustifolia (Lavender) Flower Extract', 'Mentha Arvensis Leaf Extract', 'Butylene Glycol', 'Limonene', 'Linalool'], flagged_ingredients = '[{"ingredient": "Sodium Laureth Sulfate", "reason": "sulfate"}, {"ingredient": "Ammonium Lauryl Sulfate", "reason": "sulfate"}, {"ingredient": "Dimethicone", "reason": "silicone"}, {"ingredient": "PCA Dimethicone", "reason": "silicone"}, {"ingredient": "Cetyl Triethylmonium Dimethicone PEG-8 Succinate", "reason": "silicone"}]'::jsonb, cg_status = 'not_approved', updated_at = now() WHERE id = 'b6dd32c1-a209-4879-ac22-5cd45f09bb82';

UPDATE products SET ingredients = ARRAY['Water/Aqua/Eau', 'Cetearyl Alcohol', 'Behentrimonium Chloride', 'Glycerin', 'Coco-Caprylate', 'Ethylhexyl Olivate', 'Collagen', 'Sodium Hyaluronate', 'Aloe Barbadensis Leaf Extract', 'Argania Spinosa Kernel Oil', 'Cocos Nucifera (Coconut) Oil', 'Hydrolyzed Quinoa', 'Macadamia Ternifolia Seed Oil', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'Panthenol', 'Squalane', 'Hydroxypropylgluconamide', 'Hydroxypropylammonium Gluconate', 'Hydroxypropyl Guar Hydroxypropyltrimonium Chloride', 'Tocopherol', 'Cetrimonium Chloride', 'Guar Hydroxypropyltrimonium Chloride', 'Ethylhexylglycerin', 'Citric Acid', 'Leuconostoc/Radish Root Ferment Filtrate', 'Tartaric Acid', 'Tetrasodium Glutamate Diacetate', 'Sodium Benzoate', 'Sodium Glycolate', 'Sodium Formate', 'Sodium Hydroxide', 'Potassium Sorbate', 'Benzyl Alcohol', 'Isopropyl Alcohol', 'Phenoxyethanol'], flagged_ingredients = '[{"ingredient": "Isopropyl Alcohol", "reason": "drying_alcohol"}]'::jsonb, cg_status = 'caution', updated_at = now() WHERE id = '66eece90-d739-475d-9baa-acc77b809334';

UPDATE products SET ingredients = ARRAY['Water', 'Stearyl Alcohol', 'Cetyl Alcohol', 'Stearamidopropyl Dimethylamine', 'Persea Gratissima (Avocado) Oil', 'Glutamic Acid', 'Fragrance', 'Bis-Amino Propyl Dimethicone', 'Benzyl Alcohol', 'Citric Acid', 'EDTA', 'Methylchloroisothiazolinone', 'Methylisothiazolinone'], flagged_ingredients = '[{"ingredient": "Bis-Amino Propyl Dimethicone", "reason": "silicone"}]'::jsonb, cg_status = 'not_approved', updated_at = now() WHERE id = '1b13ed49-39a0-4f6d-8ddc-6aff223c0cb8';

COMMIT;
